Fs=50e6;
T=10.^-5;
N=T/(1/Fs);
t=-T/2:1/Fs:T/2;
B=10e6;
K=B/T;
NRe=exp(1i*2*pi*K*t.^2);
Real=real(NRe);
Imag=imag(NRe);
Y=fft(NRe);
xp=angle(Y);
h=conj(NRe);
H=fft(h);
OUTPUT=H.*Y;
output=fftshift(ifft(OUTPUT));
Rectwin=rectwin(length(N));
outputwin1=NRe.*Rectwin;
OUTPUTWIN1=fft(outputwin1);
h1=conj(outputwin1);
H1=fft(h1);
OUTPUT1=H1.*OUTPUTWIN1;
outputwin11=fftshift(ifft(OUTPUT1));
Hamwin=hamming(length(N));
outputwin2=NRe.*Hamwin;
OUTPUTWIN2=fft(outputwin2);
h2=conj(outputwin2);
H2=fft(h2);
OUTPUT2=H2.*OUTPUTWIN2;
outputwin22=fftshift(ifft(OUTPUT2));
Hanwin=hann(length(N));
outputwin3=NRe.*Hanwin;
OUTPUTWIN3=fft(outputwin3);
h3=conj(outputwin3);
H3=fft(h3);
OUTPUT3=H3.*OUTPUTWIN3;
outputwin33=fftshift(ifft(OUTPUT3));
Kaiwin=kaiser(length(N));
outputwin4=NRe*Kaiwin;
OUTPUTWIN4=fft(outputwin4);
h4=conj(outputwin1);
H4=fft(h4);
OUTPUT4=H4.*OUTPUTWIN4;
outputwin44=fftshift(ifft(OUTPUT4));
subplot(441)
plot(t,Imag)
subplot(442)
plot(t,Real)
subplot(443)
plot(xp,Fs)
subplot(444)
plot(Y,Fs)
subplot(445)
plot(t,output)
subplot(446)
plot(t,outputwin1)
subplot(447)
plot(t,outputwin11)
subplot(448)
plot(t,outputwin22)
subplot(449)
plot(t,outputwin33)
subplot(4,4,10)
plot(t,outputwin44);