figure;
originalBW=imread('circles.png');
se=strel('disk',5);
erodedBW=imerode(originalBW,se);
subplot(341),imshow(originalBW),title('before eroded');
subplot(342),imshow(erodedBW),title('eroded');
l=imread('cameraman.tif');
se=strel('ball',5,5);
l2=imdilate(l,se);
subplot(343),imshow(l),title('original');
subplot(344),imshow(l2),title('dilated');
l3=imread('cameraman.tif');
se=strel('disk',5);
l4=imopen(l3,se);
subplot(345),imshow(l4),title('open');
l5=imclose(l3,se);
subplot(346),imshow(l5),title('close');
l6=imclearborder(l3);
subplot(347),imshow(l6),title('clearborder');
l7=imfill(l3);
subplot(348),imshow(l7),title('imfill');
l8=im2bw(l3);
subplot(349),imshow(l8);title('binary image');
l9=edge(l3,'sobel');
l10=edge(l3,'canny');
imview(l9);
imview(l10);